apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "argo-notifications"
spec:
  strategy:
    canary:
      canaryService: demo-canary
      stableService: demo-stable
      trafficRouting:
        nginx:
          stableIngress: demo
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: bradmccoydev/kcd-website:78cd4577509fe10071ca40739296c37ef19b0064
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources: {}
