apiVersion: v1
kind: Service
metadata:
  name: demo-canary
  namespace: demo
  labels:
    app: demo
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-stable
  namespace: demo
  labels:
    app: demo
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: demo
