helmCharts:
- name: ingress-nginx
  version: 4.0.19
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: dns-infra
  includeCRDs: true
  valuesInline: 
    controller:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
                - key: component
                  operator: In
                  values:
                    - controller
              topologyKey: "kubernetes.io/hostname"
      metrics:
        enabled: true
      publishService:
        enabled: true
      replicaCount: 2
      stats:
        enabled: true

    rbac:
      create: true

    service:
      externalTrafficPolicy: Local

    config:
      use-forwarded-headers: "true"
