apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://argocd.ortelius.io
  service.webhook.keptn: |
    url: https://keptn.ortelius.io/api/v1/event
    headers:
    - name: x-token
      value: $keptn-x-token
    - name: Content-Type
      value: application/json
  template.keptn-outofsync: |
    webhook:
      keptn:
        method: POST
        body: |
          {
            "data": {
              "configurationChange": {},
              "labels": {
                "version": "{{.app.status.sync.revision}}",
                "appname": "{{.app.metadata.name}}",
                "argocd": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              },
              "project": "{{.app.metadata.labels.keptnProject}}",
              "service": "{{.app.metadata.labels.keptnService}}",
              "stage": "{{.app.metadata.labels.keptnStage}}"
            },
            "source": "argocd",
            "specversion": "1.0",
            "type": "sh.keptn.event.dev.kickoff.triggered",
            "shkeptnspecversion": "0.2.3"
          }
  template.keptn-deployed: |
    webhook:
      keptn:
        method: POST
        body: |
          {
            "data": {
              "configurationChange": {},
              "labels": {
                "version": "{{.app.status.sync.revision}}",
                "appname": "{{.app.metadata.name}}",
                "link": "{{.app.metadata.annotations.externalURI}}",
                "buildId": "{{.app.status.sync.revision}}",
                "argocd": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              },
              "deployment": {
                  "deploymentURIsPublic": [
                     "{{.app.metadata.annotations.externalURI}}"
               ]
              },
              "project": "{{.app.metadata.labels.keptnProject}}",
              "service": "{{.app.metadata.labels.keptnService}}",
              "stage": "{{.app.metadata.labels.stage}}",
              "repository": "{{.app.spec.source.repoURL}}",
              "result": "pass"
            },
            "source": "argocd",
            "specversion": "1.0",
            "type": "sh.keptn.event.deliver.finished",
            "shkeptnspecversion": "0.2.3",
            {{$first := true}}
            {{- range $index,$value := .app.status.operationState.operation.info}}
              {{- if $first}}
                  {{- $first = false}}
              {{- else}}
                  ,
              {{- end}}
            "{{$value.name}}": "{{$value.value}}"
            {{- end}}
          }
  trigger.on-out-of-sync-status: |
    - when: app.status.sync.status == 'OutOfSync'
      send: [keptn-outofsync]
  trigger.on-deployed: |
    - when: app.status.sync.status == 'Synced' and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [keptn-deployed]
